// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: harness.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_harness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateSessionRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionMessage        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_harness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSession() *SessionMessage {
	if x != nil {
		return x.Session
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_harness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_harness_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_harness_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{4}
}

func (x *GetRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *RunMessage            `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunResponse) Reset() {
	*x = GetRunResponse{}
	mi := &file_harness_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunResponse) ProtoMessage() {}

func (x *GetRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunResponse.ProtoReflect.Descriptor instead.
func (*GetRunResponse) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{5}
}

func (x *GetRunResponse) GetRun() *RunMessage {
	if x != nil {
		return x.Run
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromSeq       int64                  `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_harness_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{6}
}

func (x *StreamEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamEventsRequest) GetFromSeq() int64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

type EventMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_harness_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{7}
}

func (x *EventMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EventMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EventMessage) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *EventMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *EventMessage) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_harness_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{8}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_harness_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{9}
}

type CancelRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_harness_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{10}
}

func (x *CancelRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type CancelRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunResponse) Reset() {
	*x = CancelRunResponse{}
	mi := &file_harness_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunResponse) ProtoMessage() {}

func (x *CancelRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunResponse.ProtoReflect.Descriptor instead.
func (*CancelRunResponse) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{11}
}

type SessionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage) Reset() {
	*x = SessionMessage{}
	mi := &file_harness_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage) ProtoMessage() {}

func (x *SessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage.ProtoReflect.Descriptor instead.
func (*SessionMessage) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{12}
}

func (x *SessionMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionMessage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SessionMessage) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *SessionMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RunMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StepCount     int32                  `protobuf:"varint,4,opt,name=step_count,json=stepCount,proto3" json:"step_count,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,5,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ended_at,json=endedAt,proto3,oneof" json:"ended_at,omitempty"`
	Error         *RunErrorMessage       `protobuf:"bytes,8,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunMessage) Reset() {
	*x = RunMessage{}
	mi := &file_harness_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMessage) ProtoMessage() {}

func (x *RunMessage) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMessage.ProtoReflect.Descriptor instead.
func (*RunMessage) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{13}
}

func (x *RunMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunMessage) GetStepCount() int32 {
	if x != nil {
		return x.StepCount
	}
	return 0
}

func (x *RunMessage) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *RunMessage) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RunMessage) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *RunMessage) GetError() *RunErrorMessage {
	if x != nil {
		return x.Error
	}
	return nil
}

type RunErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunErrorMessage) Reset() {
	*x = RunErrorMessage{}
	mi := &file_harness_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunErrorMessage) ProtoMessage() {}

func (x *RunErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunErrorMessage.ProtoReflect.Descriptor instead.
func (*RunErrorMessage) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{14}
}

func (x *RunErrorMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RunErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_harness_proto protoreflect.FileDescriptor

const file_harness_proto_rawDesc = "" +
	"\n" +
	"\rharness.proto\x12\aharness\x1a\x1fgoogle/protobuf/timestamp.proto\"Q\n" +
	"\x14CreateSessionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\"J\n" +
	"\x15CreateSessionResponse\x121\n" +
	"\asession\x18\x01 \x01(\v2\x17.harness.SessionMessageR\asession\"M\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x13SendMessageResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"&\n" +
	"\rGetRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"7\n" +
	"\x0eGetRunResponse\x12%\n" +
	"\x03run\x18\x01 \x01(\v2\x13.harness.RunMessageR\x03run\"O\n" +
	"\x13StreamEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x03R\afromSeq\"\xb0\x01\n" +
	"\fEventMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12*\n" +
	"\x02at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14CloseSessionResponse\")\n" +
	"\x10CancelRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x13\n" +
	"\x11CancelRunResponse\"\xae\x01\n" +
	"\x0eSessionMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd6\x02\n" +
	"\n" +
	"RunMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"step_count\x18\x04 \x01(\x05R\tstepCount\x12\x1f\n" +
	"\vtokens_used\x18\x05 \x01(\x05R\n" +
	"tokensUsed\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12:\n" +
	"\bended_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\aendedAt\x88\x01\x01\x123\n" +
	"\x05error\x18\b \x01(\v2\x18.harness.RunErrorMessageH\x01R\x05error\x88\x01\x01B\v\n" +
	"\t_ended_atB\b\n" +
	"\x06_error\"?\n" +
	"\x0fRunErrorMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbd\x03\n" +
	"\x0eHarnessService\x12N\n" +
	"\rCreateSession\x12\x1d.harness.CreateSessionRequest\x1a\x1e.harness.CreateSessionResponse\x12K\n" +
	"\fCloseSession\x12\x1c.harness.CloseSessionRequest\x1a\x1d.harness.CloseSessionResponse\x12H\n" +
	"\vSendMessage\x12\x1b.harness.SendMessageRequest\x1a\x1c.harness.SendMessageResponse\x129\n" +
	"\x06GetRun\x12\x16.harness.GetRunRequest\x1a\x17.harness.GetRunResponse\x12E\n" +
	"\fStreamEvents\x12\x1c.harness.StreamEventsRequest\x1a\x15.harness.EventMessage0\x01\x12B\n" +
	"\tCancelRun\x12\x19.harness.CancelRunRequest\x1a\x1a.harness.CancelRunResponseB3Z1github.com/daobathanh/celesnity/transport/grpc/pbb\x06proto3"

var (
	file_harness_proto_rawDescOnce sync.Once
	file_harness_proto_rawDescData []byte
)

func file_harness_proto_rawDescGZIP() []byte {
	file_harness_proto_rawDescOnce.Do(func() {
		file_harness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_harness_proto_rawDesc), len(file_harness_proto_rawDesc)))
	})
	return file_harness_proto_rawDescData
}

var file_harness_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_harness_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),  // 0: harness.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 1: harness.CreateSessionResponse
	(*SendMessageRequest)(nil),    // 2: harness.SendMessageRequest
	(*SendMessageResponse)(nil),   // 3: harness.SendMessageResponse
	(*GetRunRequest)(nil),         // 4: harness.GetRunRequest
	(*GetRunResponse)(nil),        // 5: harness.GetRunResponse
	(*StreamEventsRequest)(nil),   // 6: harness.StreamEventsRequest
	(*EventMessage)(nil),          // 7: harness.EventMessage
	(*CloseSessionRequest)(nil),   // 8: harness.CloseSessionRequest
	(*CloseSessionResponse)(nil),  // 9: harness.CloseSessionResponse
	(*CancelRunRequest)(nil),      // 10: harness.CancelRunRequest
	(*CancelRunResponse)(nil),     // 11: harness.CancelRunResponse
	(*SessionMessage)(nil),        // 12: harness.SessionMessage
	(*RunMessage)(nil),            // 13: harness.RunMessage
	(*RunErrorMessage)(nil),       // 14: harness.RunErrorMessage
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_harness_proto_depIdxs = []int32{
	12, // 0: harness.CreateSessionResponse.session:type_name -> harness.SessionMessage
	13, // 1: harness.GetRunResponse.run:type_name -> harness.RunMessage
	15, // 2: harness.EventMessage.at:type_name -> google.protobuf.Timestamp
	15, // 3: harness.SessionMessage.created_at:type_name -> google.protobuf.Timestamp
	15, // 4: harness.RunMessage.started_at:type_name -> google.protobuf.Timestamp
	15, // 5: harness.RunMessage.ended_at:type_name -> google.protobuf.Timestamp
	14, // 6: harness.RunMessage.error:type_name -> harness.RunErrorMessage
	0,  // 7: harness.HarnessService.CreateSession:input_type -> harness.CreateSessionRequest
	8,  // 8: harness.HarnessService.CloseSession:input_type -> harness.CloseSessionRequest
	2,  // 9: harness.HarnessService.SendMessage:input_type -> harness.SendMessageRequest
	4,  // 10: harness.HarnessService.GetRun:input_type -> harness.GetRunRequest
	6,  // 11: harness.HarnessService.StreamEvents:input_type -> harness.StreamEventsRequest
	10, // 12: harness.HarnessService.CancelRun:input_type -> harness.CancelRunRequest
	1,  // 13: harness.HarnessService.CreateSession:output_type -> harness.CreateSessionResponse
	9,  // 14: harness.HarnessService.CloseSession:output_type -> harness.CloseSessionResponse
	3,  // 15: harness.HarnessService.SendMessage:output_type -> harness.SendMessageResponse
	5,  // 16: harness.HarnessService.GetRun:output_type -> harness.GetRunResponse
	7,  // 17: harness.HarnessService.StreamEvents:output_type -> harness.EventMessage
	11, // 18: harness.HarnessService.CancelRun:output_type -> harness.CancelRunResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_harness_proto_init() }
func file_harness_proto_init() {
	if File_harness_proto != nil {
		return
	}
	file_harness_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_harness_proto_rawDesc), len(file_harness_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_harness_proto_goTypes,
		DependencyIndexes: file_harness_proto_depIdxs,
		MessageInfos:      file_harness_proto_msgTypes,
	}.Build()
	File_harness_proto = out.File
	file_harness_proto_goTypes = nil
	file_harness_proto_depIdxs = nil
}
